version: "3.9"

services:
  synapse-backend:
    build: .
    container_name: synapse_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./vector_store:/app/vector_store
    environment:
      - DATABASE_URL=sqlite:///./app/synapse.db
      - VECTOR_STORE_PATH=/app/vector_store/faiss.index
      - STT_API_KEY=
      - TTS_API_KEY=
      - MAX_FREE_TOKENS=1000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload